<?php 

$home2=$http.'index2.php';
$price2=$http.'price2.php';
$tech2=$http.'new2.php';
$help2=$http.'question2.php';
$pc2=$http.'pc2.php';
$sibanet2=$http.'sibanet2.php';
$receiver2=$http.'receiver2.php';
$phone2=$http.'phone2.php';
$website2=$http.'website2.php';
$photo2=$http.'picture2.php';
$sound2=$http.'sound2.php';
$download2=$http.'download2.php';
$us2=$http.'us2.php';
$new2=$http.'new2.php';
$mail2=$http.'mail2.php';
$question2=$http.'question2.php';
?>